@LibraryApi_HostAddress = https://localhost:7208


GET {{LibraryApi_HostAddress}}/api/authors

###

POST {{LibraryApi_HostAddress}}/api/authors
Content-Type: application/json

{
  "firstName": "Trevor",
  "lastName": "Noah"
}

###

GET {{LibraryApi_HostAddress}}/api/authors/1

###

DELETE {{LibraryApi_HostAddress}}/api/authors/1

###

GET {{LibraryApi_HostAddress}}/api/books

###

POST {{LibraryApi_HostAddress}}/api/books
Content-Type: application/json

{
  "isbn": "123456789",
  "title": "Born a Crime",
  "publishedYear": 2016,
  "authorIds": [
    1
  ]
}

###

GET {{LibraryApi_HostAddress}}/api/books/1

###

DELETE {{LibraryApi_HostAddress}}/api/books/1

###
GET {{LibraryApi_HostAddress}}/api/members

###

POST {{LibraryApi_HostAddress}}/api/members
Content-Type: application/json

{
  "memberNr": 123456,
  "firstName": "Jason",
  "lastName": "Bourne"
}

###

GET {{LibraryApi_HostAddress}}/api/members/1

###

DELETE {{LibraryApi_HostAddress}}/api/members/1

###

GET {{LibraryApi_HostAddress}}/api/loans

###

POST {{LibraryApi_HostAddress}}/api/loans
Content-Type: application/json

{
  "memberId": 1,
  "bookId": 1
}

###

GET {{LibraryApi_HostAddress}}/api/loans/1

###

PATCH {{LibraryApi_HostAddress}}/api/loans/return/1

###


GET {{LibraryApi_HostAddress}}/api/ratings

###

POST {{LibraryApi_HostAddress}}/api/ratings
Content-Type: application/json

{
  "memberId": 1,
  "bookId": 1,
  "ratingValue": 10,
  "comment": "This is a great book!"
}

###

GET {{LibraryApi_HostAddress}}/api/ratings/1

###

DELETE {{LibraryApi_HostAddress}}/api/ratings/1

###
